package dev.oianmol.opentestlab.tasks

import kotlin.Result
import kotlin.coroutines.cancellation.CancellationException

suspend fun <R> runCatchingCancellable(block: suspend () -> R): Result<R> {
    return try {
        Result.success(block())
    } catch (c: CancellationException) {
        throw c
    } catch (e: Throwable) {
        Result.failure(e)
    }
}